config/routes.rb
Toffoli::Application.routes.draw do

  root :to => 'site#index', :locale => 'pt-BR'
  scope '(:locale)', :locale => /en|pt-BR/ do
    root :to => 'site#index', :as => 'root_locale'

    get 'articles' => 'articles#index', :as => 'all_articles'
    get 'articles.atom' => 'articles#index', :format => 'atom', :as => 'main_feed'
    get 'articles/:slug' => 'articles#show'
    get 'articles/:category.atom' => 'articles#feed', :format => 'atom', :as => 'category_feed'
    get 'articles/*slug' => 'articles#show', :as => 'slug'
    get 'articles/feed' => 'articles#feed', :as => 'feed'
    match ':controller(/:action(/:id(.:format)))'
  end
end

app/models/article.rb
class Article
  attr_accessor :category_url, :info, :body, :url
  def self.all(category_url=nil)
    find("#{category_url}/**/*", true)
  end

  def self.find(article_url, return_array = false)
    articles_root = Rails.root + "articles/#{I18n.locale}"
    result = Pathname.glob("#{articles_root}/#{article_url}.txt").collect { |p|
      begin
        a = Article.new
        a.url = (rel=p.realpath.relative_path_from(articles_root)).sub(/.txt\z/,'')
        a.category_url = rel.dirname.to_s
        header, body = p.read.split("\n\n", 2)
        a.info = YAML.load(header)
        puts "info = #{a.info['updated_at']}"
        a.body = body
      rescue Exception => ex
        Rails.logger.error "Error processing YAML: #{p} - #{ex}"
        next nil
      end
      a
    }.compact.sort{|a,b| b.created_at <=> a.created_at}
    return result if return_array
    result.first
  end

  def self.last_articles(number=3)
    all().sort_by(&:updated_at).take number
  end

  def summary 
      #config = @config[:summary]
      max_length = 100
      delim = /[\t|\s]+?$/
      sum = (self.body =~ delim) ? self.body.split(delim).first : self.body.match(/(.{1,#{max_length}}.*?)(\n|\Z)/m).to_s
      Markdown.new((sum.length == self.body.length ? sum : sum.strip.sub(/\.\Z/, '&hellip;')).to_s.strip).to_html.html_safe
  end

  def created_at
    @created_at ||= parse_date(info['created_at'])
  end

  def updated_at
    @updated_at ||= parse_date(info['updated_at']) || created_at
  end

  def title
    @title ||= info['title']
  end

  def body_html
    Markdown.new(body.gsub(/^@@@ (\w+)\n(.*?)^@@@$/m){%Q{<div style="overflow: auto">
      #{CodeRay.scan($2, $1).div(:line_numbers => :table)}</div>}}).to_html.html_safe
  end

  def category
    Category.find category_url
  end

  def full_url
    "/#{I18n.locale}/articles/#{url}"
  end

  def slug(locale)
    "#{url.dirname.to_s + '/' if url.dirname.to_s != '.'}#{info["slug_#{locale}"]}"
  end
 private
  def parse_date(date)
    (DateTime.strptime(date, "%d/%m/%Y %H:%M") rescue DateTime.strptime(date, "%d/%m/%Y")).to_time rescue nil
  end
end

app/models/category.rb
class Category
  attr_accessor :info, :url, :system_path, :index_path
  def self.all(parent=nil)
    find("#{parent}/*", true).sort_by &:order
    #find("#{parent}/*", true).sort_by {|c| c.order}
  end

  def self.find(url, return_array = false)
    articles_root = Rails.root + "articles/#{I18n.locale}"
    res = Pathname.glob("#{articles_root}/#{url}/").collect { |path|
      Category.new.tap do |c|
        c.info = YAML.load(((c.system_path = path.realpath) + 'info.yml').read) rescue {}
        c.url = c.system_path.relative_path_from(articles_root).to_s
        c.index_path = path + 'index.html.erb'
        c.index_path = nil unless c.index_path.exist?
      end
    }
    return res if return_array
    res.first rescue nil
  end

  def title
    info['title']
  end

  def description
    info['description']
  end

  def order
    info['order']
  end
  
  def articles
    @articles ||= Article.all(url)
  end
end

app/controllers/application_controller.rb
# Filters added to this controller apply to all controllers in the application.
# Likewise, all the methods added will be available for all controllers.

class ApplicationController < ActionController::Base
  helper :all # include all helpers, all the time
  protect_from_forgery # See ActionController::RequestForgeryProtection for details

  before_filter :set_locale, :set_categories
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale    
  end
  def set_categories
    @categories = Category.all    
  end

  def default_url_options(options = {})
    {:locale => I18n.locale}
  end
  # Scrub sensitive parameters from your log
  # filter_parameter_logging :password
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  def index
    @articles = Article.all('**')
    respond_to do |format|
      format.html
      format.atom do
        @title = 'Bruno Rocha Toffoli'
        render :action => 'feed'
      end
    end
  end

  def show
    slug = params[:slug]
    unless @article = Article.find(slug)
      @category = Category.find(slug)
      unless @category
        render :text => t('article.not_found'), :status => 404, :layout => true
        return
      end
      @title = "Bruno Rocha Toffoli - #{@category.title}"
      render @category.index_path ? {:file => @category.index_path, :layout => true} :
        {:action => :show_category}
      return
    end
    @title = "Bruno Rocha Toffoli - #{@article.title}"
  end

  def feed
    # @category = Category.find params[:category]
    puts "ssscategory -> #{@category}"
    @articles = @category ? @category.articles : Article.all? { '**' }
    @title = "Bruno Rocha Toffoli - #{@category.title}"
    respond_to {|f| f.atom}
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
    @last_articles = Article.last_articles 2
  end

  def about

  end

  def curriculum
    render :layout => false
  end
end

app/helpers/application_helper.rb
# encoding: utf-8
# Methods added to this helper will be available to all templates in the application.
module ApplicationHelper
  def menu_link(title, slug)
    link_to title, slug_url(:slug => slug)
  end

  def root_path
    "http://#{request.host_with_port}"
  end

  def markdown_content(&content)
    Markdown.new(capture(&content)).to_html.html_safe
  end

  def change_locale_link
    locale = I18n.locale.to_s == 'en' ? 'pt-BR' : 'en'
    description = I18n.locale.to_s == 'en' ? 'Versão em português' : 'English version'
    options = request.path_parameters.merge(:locale => locale)
    options.merge!(:slug => @article.slug(locale).split('/')) if @article
    return link_to description, options
  end

  if Rails.env.production?
    def hosted_image_path(source)
      "http://usera.imagecave.com/toffoli/site/#{source}"
    end

    def hosted_image_tag(source, options={})
      image_tag hosted_image_path(source), options
    end
  else
    def hosted_image_path(source)
      image_path(source)
    end

    def hosted_image_tag(source, options={})
      image_tag source, options
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/articles/index.html.erb
<% @articles.each do |article| %>
  <div><%= link_to article.title, "/#{I18n.locale}/articles/#{article.url}" %> (<%= l(article.created_at) %>)</div>
<% end %>

app/views/articles/show.html.erb
<% content_for :header do %>
  <%= stylesheet_link_tag 'markdown/coderay' %>
  <%= javascript_tag do %>
    disqus_developer = 1
  <% end if Rails.env.development? %>
<% end %>
<h1><%= @article.title %></h1>
<div><%=l @article.created_at %> 
	<%= '(' + t('article.updated_at', 
	:date => l(@article.updated_at)) + ')' if @article.info['updated_at'] %>
</div>

<section class="content">
  <%= @article.body_html %>
</section>

<section class="comments">
  <div id="disqus_thread"></div>
  <script type="text/javascript" src="http://disqus.com/forums/blogsbtoffoli/embed.js"> </script>
  <noscript><a href="http://blogsbtoffoli.disqus.com/?url=ref"><%= t('disqus.view_discussion_thread') %></a></noscript>
  <a href="http://disqus.com" class="dsq-brlink"><%= t('disqus.comments_powered_by') %><span class="logo-disqus">Disqus</span></a>
  <a name="comments"></a>
</section>

app/views/articles/show_category.html.erb
<% content_for :header do %>
  <%= auto_discovery_link_tag :atom, {:controller => :articles, :action => 'feed', :format => 'atom', :category => @category.url},
                              :title => "Bruno Rocha Toffoli - #{@category.title}" %>
<% end %>
<h1><%= @category.title %></h1>

<%=raw Markdown.new(@category.description.to_s).to_html %>

<% @category.articles.each do |article| %>
  <div><%= link_to article.title, :slug => article.url.to_s.split('/') %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<!-- *Do note Remove this* -->
	<!--Designed by : Roshan
	Website : www.ramblingsoul.com
	email : c.pixels@gmail.com
	-->
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
		<title>Bruno Rocha Toffoli</title>
		<meta name="description" content="Here goes your description" />
		<meta name="keywords" content="here, goes, your key, words, keywords,.." />
		<meta name="author" content="Your Name" />
		<%= stylesheet_link_tag 'style', :media => :screen %>
		<%= javascript_include_tag 'http://www.google-analytics.com/ga.js' %>
		<%= yield :header %>
	</head>
	<body>
		<div id="wrap">
			<div id="tophead"></div>
			<div id="header">
				<div id="logo">
					<h1 class="logotext"><!-- <%= link_to "Bruno", root_locale_path(:locale => I18n.locale) %>--> B<span>r</span>u<span>n</span>o <span>T</span>o<span>f</span>f<span>o</span>l<span>i</span></h1>
				</div>
				<div id="navigation">
					<ul>
						<li>
							<a title="Contato" href="#">Contato</a>
						</li>
						<li>
							<%= link_to t('layout.navigation_menu.curriculum'), {:controller => 'site', :action => 'curriculum'}, :target => '_blank' %>
						</li>
						<li>
							<%= link_to t('layout.navigation_menu.about'), :controller => 'site', :action => 'about' %>
						</li>
						<!--<li><a title="Home" class="current" href="#">Home</a></li>-->
						<li>
							<%= link_to t('layout.navigation_menu.home'), root_locale_path(:locale => I18n.locale) %>
						</li>
					</ul>
				</div>
				<div id="infobox">
					<h1>Olá, Seja Bem Vindo!</h1>
					<span>
						<p>
							Este é um espaço onde procuro organizar algumas informações que considero interessantes, voltadas principalmente para
							desenvolvimento de sistemas para a web, além de pensamentos diversos sobre Informática em geral.
						</p> </span>
				</div>
			</div>
			<div id="sidenotes">
				<div class="sidenav">
					<ul>
						<!--<li><%= link_to t('layout.navigation_menu.all_articles'), all_articles_path %></li>-->
						<!--<li><%= menu_link 'Ruby / Rails', 'ruby-rails' %></li>-->
						<% @categories.each do |category| %>
						<li>
							<%= menu_link "#{category.title}", category.url%>
						</li>
						<% end %>
					</ul>
				</div>
			</div>
			<div id="contents">
				<%= yield %>
			</div>
			<div id="footer">
				<div class="rsslinks">
					<%= link_to t("layout.navigation_menu.feeds #{@category ? @category.title : ''}"), url_for(:main_feed)
						# TODO Fazer link por categoria
					%>
				</div>				
			</div>
		</div>
		<div id="bottompage">
			<div id="inner">
				<span><a href="#">Back to Top</a></span>
				<!--Removing this link back to my website will be violation of Creative Commons License, under which this template is released for download
				-->
				<a href="http://www.ramblingsoul.com" title="rambles and rants, Design portfolio, Brunei Web Designer">Design : RamblingSoul</a>
				<!-- Copyright - Roshan -->
			</div>
		</div>
		<%= javascript_tag do %>
			var _gaq = _gaq || [];
			_gaq.push(['_setAccount', 'UA-25343576-1']);
			_gaq.push(['_setDomainName', '.btoffoli.com']);
			_gaq.push(['_trackPageview']);
	
			(function() {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			})();
		<% end if Rails.env.production? %>
	</body>
</html>

app/views/site/about.en.html.erb
<%= content_for :header do %>
  <style type="text/css">
    body > section img {width: 200px; margin: 0 1em}
  </style>
<% end %>
<%= markdown_content do %>
[About the author](#author)

[About the site](#site)

#<a name="author">About the author</a>

<%= hosted_image_tag 'eu-chapeu.jpg', :alt => 'Me with a hat', :style => 'float: left' %>
<%= hosted_image_tag 'sabrina-rodrigo-com-nuvens.jpg', :alt => 'Sabrina and Rodrigo', :style => 'float: right' %>

I am a lover of good music, surfing, Science & Technology, besides my adorable wife, of course.

<p style="clear:right">Since I was a kid, I am curious about several subjects such as machines, life, universe,
musical instruments, human psychology and everything else that interest me. In other words, I was a typical child. And,
like every child, the primary means to satisfy the curiosity is through experimentation. This typically involved
disassembling (and assembling again) my clock, all broken equipments (and some more that were not broken yet), trying to
fix them and create new great stuff, such as building a hut, mixing elements to see what happens (what I would understand
later that it was part of the Chemistry science, which is coincidentally the formation area of my wife), in addition to
creating music.</p>

<%= hosted_image_tag 'rodrigo-cavaco.jpg', :alt => 'Rodrigo with a cavaco', :style => 'float: right' %>

I must confess that I was not good in any of that, except maybe with the clocks and some electronic equipments with
poor contact, but that didn't matter either. The final result was less interesting to me than learning. For some reason,
after this stage, strangely, schools (at least in Brazil) seem to create a feeling on students that studying is a boring
task and lots of them get away from science, exactly when they start frequenting schools.

<%= hosted_image_tag 'rodrigo-violao-noel.jpg', :alt => 'Rodrigo with the guitar', :style => 'float: left' %>

That didn't happen to me. Despite the discouragement caused by schools (and I've studied in lots of them in my childhood,
so that was not a problem specific to some schools), I always have been curious. Eventually, I ended up dedicating
myself to some specific areas and lost the general interest I had when I was a child. School takes us a lot of time,
leaving too little time for practicing science, studying and experimenting with scientific methods.

The interest in electronics led me through an Electrical Engineering formation, although I was also interested in
Computer and Mechanics. My father always incentived me on studying computers, since I was 10 years old. He was a partner
in a TI company and, watching my interest on computers and electronics, in general, enrolled me in several courses, as
DBase3/DOS, Clipper, Delphi and others over time. Interestingly, none of these courses was the basis of knowledge I
acquired with computers. Most came from experimentation and research on my own. The courses followed the traditional
model of schools, providing cookbooks, instead of explaining the concepts behind the presented code.

<%= hosted_image_tag 'rodrigo-rails-summit-2009.jpg', :alt => 'Rodrigo on Rails Summit 2009', :style => 'float: right' %>

Studying on my own, I learned a lot about operating systems and programming in general, experiencing over the years
several programming languages, through the compiled ones as Clipper, C/C++, (Object) Pascal, Assembly and Java, to
scripting languages such as Perl, Matlab, Scilab, shell scripting, VBScript, Ruby, Groovy and JavaScript. I confess that
I have not had interest yet in purely functional languages such as LISP and Haskell. I also read a little about Scala
and it seems to be an interesting language to what it is proposed for.

<%= hosted_image_tag 'sabrina-rodrigo-santa-teresa.jpg', :alt => 'Rodrigo and Sabrina at Santa Teresa', :style => 'float: left' %>

I was also a bit curious to know PHP and Python, but I didn't find any useful additional features when compared to other
languages I already knew. I don't like to be forced to organize my code with a fixed rule (the forced indentation of
Python and the lack of a block terminator) and I think that PHP was designed to be an alternative to ASP, encouraging a
code style that is a mixture of HTML and programming logic, which is bad for maintenance of a system. Later, there were
frameworks for PHP to promote a MVC model, inspired by Rails and others, but I see no advantage when compared to the
original ones.

The languages to which I paid more attention were C, C++ and Ruby, but has had enough experience with Delphi and Perl
with some work I've done. And, as Ruby is currently my favorite language, most of the technical papers of this site will
talk about Ruby and Rails, my favorite framework for Web development.

#<a name="site">About the site</a>

## Why another site/blog?

Good question. In fact, fortunately, there are excellent sources of knowledge available on the web about the various
existent technologies, especially in computer science and programming. I've subscribed for several blog feeds that I
read every day by really smart authors. So this is a valid question: why another one?

It turns out that each individual has their own experience, accumulated over time and observe differently the same
situation observed by another individual. In addition, each one has their way of reporting this experience. Likewise,
each individual learns best with a different writing style. Therefore, I believe that there is no limit to the amount of
good available information, whether in books, websites or blogs.

I intend to address the subjects in my articles here in the way I would like to read them. The more I think about the
difficulty that beginners have to assimilate all this technology and select which source of information to look for,
the more I worry about them. So I decided to create a more complete material dealing with basic to advanced in a way
that a layman can follow investing as little time as possible.

The strategy that I outlined to achieve this goal was to start with a series of articles that would become in the future
parts of a more organized and complete material. I also want to share some thoughts about issues that have interested me
as well as exchanging experiences in the form of comments.

## Why not a traditional blog?

The trend is very strong for building blogs. I understand perfectly, because through them, it is possible that a
non-technical person in the area of web design can express their opinions and share information easily. But is this the
best option for those who have no problem in organizing their sites in a custom way?

I never really liked blogs. First, I do not like the name "blog" or "weblog" (my site is not a log), but this is not the
main reason. A blog is also a site, but taking a look at the self-declared blogs out there, I associated this concept to
some form of organization of a site. In this model, the articles are treated as disposable short-lived information.
This is not my intention.

Furthermore, the search for new articles is favored but, in the other side, finding old news is not that easy.
Organization is accomplished purely by date or, additionally, by tags that say not much. The idea is that an article
should be rarely updated and it is natural that it would become obsolete shortly. Definitely, this is not the project I
have for my site.

However, blogs also have good ideas. The main one, in my opinion, is the availability of news feeds. With them, one can
follow the news that are being written by someone or organization in a news aggregator, without the need to often access
the site / blog or having to sign up for mailing lists. The second best idea is the interaction with readers in the form
of comments. This enables rich discussions, where all players benefit.

Summarizing, this site is organized the way that I believe is the most efficient one to organize several subjects. I do
hope you find something of value in the available content and I will be happy to discuss these issues through the comments.

Enjoy a good reading!
<% end %>

app/views/site/about.pt-BR.html.erb
<%= content_for :header do %>
  <style type="text/css">
    body > section img {width: 200px; margin: 0 1em}
  </style>
<% end %>
<%= markdown_content do %>


<!--<%= hosted_image_tag 'eu-chapeu.jpg', :alt => 'Eu de chapéu', :style => 'float: left' %>-->
<!--<%= hosted_image_tag 'sabrina-rodrigo-com-nuvens.jpg', :alt => 'Sabrina e Rodrigo', :style => 'float: right' %>-->


<p style="clear:right">
  Eu sou um fissurado por tecnologia, não me prendo a tecnologia nem tampouco defendo uma ou outra assiduamente. Não entro em discussões do tipo minha tecnologia é melhor que a sua, blabla, etc...
  Enfim eu acredito que determinada tecnlogia, linguagem, framework, plugins e outros se aplicam melhor a determinado projeto.

</p>

<!--<%= hosted_image_tag 'rodrigo-cavaco.jpg', :alt => 'Rodrigo com o cavaco', :style => 'float: right' %>-->


<!--<%= hosted_image_tag 'rodrigo-violao-noel.jpg', :alt => 'Rodrigo com o violão', :style => 'float: left' %>-->


<!--<%= hosted_image_tag 'rodrigo-rails-summit-2009.jpg', :alt => 'Rodrigo na Rails Summit 2009', :style => 'float: right' %>-->


<!--<%= hosted_image_tag 'sabrina-rodrigo-santa-teresa.jpg', :alt => 'Rodrigo e Sabrina em Santa Teresa', :style => 'float: left' %>-->


<% end %>

app/views/site/curriculum.en.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Curriculum Vitae</title>
  <meta name="AUTHOR" content="Rodrigo Rosenfeld Rosas" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <style type="text/css">
    h3 {text-decoration: underline;}
    h3.subtopic {text-decoration: none; margin-left: 2em;}
    div.subtopic {margin-left: 4em;}
    div.description {margin-left: 1em;}
  </style>
</head>
<body>

<h1>Curriculum Vitae</h1>
<hr />
<h2>Rodrigo Rosenfeld Rosas</h2>
<div>Presidente Pedreira, 145, ed. Vicmar, ap. 602, Parque Moscoso</div>
<div>Vitória, ES</div>
<div>Brazil - 29018-025</div>
<div>Phone: (27) 3082-6309 / 8803-2664</div>
<div>rr_rosas@yahoo.com.br, rr.rosas@gmail.com</div>
<div><a href="http://rosenfeld.heroku.com">http://rosenfeld.heroku.com</a></div>

<h3>Education</h3>
<div class="subtopic">
  <div>Universidade Federal do Espírito Santo</div>
  <div>Master in Automation, 2004-2006</div>
  <div>Master Thesis: <em>A Real-Time Mobile Robotic Framework</em></div>
  <div><strong>Note:</strong> for validating the above thesis, I built a real-time frame-grabber kernel module for Linux, using the Xenomai real-time extension.</div>
  <hr />
  <div>Graduate in Electrical Engineering, 1999-2004</div>
  <div>Final graduate project: <em>A Galvanostat/Potentiostat Interactive with PC</em></div>
  <hr />
  <div>MEC National College Evaluation Exam, 2003</div>
  <div>Got maximum score: 100</div>
  <hr />
  <div>Scientific Initiatory Project: <em>Developing Strategies for Coordinating Multiple Mobile Robots for Moving Objects</em>, 2002-2004</div>
  <hr />
  <div>Scientific Initiatory Project: <em>A Virtual Lab for Teaching Electromagnetism</em>, 2001</div>
  <hr />
  <div>Electro-technical High Scool, 1995-1999</div>
</div>

<h3>Publishing and Event Participation</h3>
<div class="subtopic">
  <div><a href="http://rubygems.org">RubyGems</a> (2010)
    <ul>
      <li>Author of <a href="http://rubygems.org/gems/rails-web-console">rails-web-console</a> gem.</li>
    </ul>
  </div>
  <div><a href="http://railsmagazine.com">Rails Magazine</a> (2009)
    <ul>
      <li>Published the article <em>Generating PDF with ODF templates</em> on <a href="http://railsmagazine.com/issues/4">issue #4</a>.</li>
    </ul>
  </div>
  <div>Events:  
    <ul>
      <li><a href="http://rubyconf.com.br"><em>RubyConf Brasil</em></a> (2010);</li>
      <li><a href="http://www.mare-vix.com"><em>Maré de agilidade</em></a> (2010);</li>
      <li><a href="http://www.railssummit.com.br/"><em>Rails Summit Latin America</em></a> (2009);</li>
      <li><a href="http://www.conisli.org.br/">Congresso Internacional de Software Livre - CONISLI</a>, 2007, São Paulo.</li>
    </ul>
  </div>
</div>

<h3>Jobs</h3>
<div class="subtopic">
  <div><a href="http://www.geocontrol.com.br">Geocontrol</a>, (since 2009, April)</div>
  <div>Software Developer (languages: Javascript, Groovy (framework Grails) and Java):
    <ul>
      <li>GPS tracking and map based web system development;</li>
      <li>Deployed Git, Gitorious, Redmine, DHCP and DNS server on internal infrastructure;</li>
    </ul>
  </div>

  <hr />

  <div><a href="http://www.fapes.es.gov.br">Fundação de Apoio à Ciência e Tecnologia do Espírito Santo - FAPES</a>, 2007-2009</div>
  <div>TI consultant:
    <ul>
      <li>Web development with Ruby on Rails and maintenance of a legacy ASP web system;</li>
      <li>Responsible for TI infrastructure (servers deployment, firewall, backup, user management, security policy, contracts, help-desk, etc).</li>
    </ul>
  </div>

  <hr />

  <div>RBS Tecnologia da Informação, 2006-2007</div>
  <div>Software development for automated parking system with Delphi and Firebird.</div>

  <hr />

  <div><a href="http://www.metropolitanavix.com.br/">Instituição Metropolitana de Vitória</a>, 2006-2007</div>
  <div>Teaching Analogic Electronics classes in a Technical Electronics Course.</div>

  <hr />

  <div>Riberdiscap, 2004</div>
  <div>Development of Riberdiscap site (not a job, actually).</div>

  <hr />

  <div><a href="http://www.sindaees.com.br">Sindaees</a>, 2002</div>
  <div>Development of Sindaees site.</div>

  <hr />

  <div>Núcleo de Ciências - ProEx, UFES, 2000-2002</div>
  <div>Development of their site and other softwares for their projects and computer maintenance;</div>

  <hr />

  <div>RBS Tecnologia da Informação, 1999</div>
  <div>Computer maintenance.</div>
</div>

<h3 class="subtopic">Technical Experience</h3>
<div class="subtopic">
  <ul>
    <li>Strong experience with web 2.0 geolocation based applications (using the OpenLayers javascript library).</li>
    <li>Proficent gVim user.</li>
    <li>Programming languages: I had developed from ancient languages in the past such as Assembly, Fortran, C, C++, Perl and Clipper to newer ones such as Ruby, Groovy, Java, JRuby among others, being Ruby my favorite one.</li>
    <li>Web standards: HTML, XHTML, CSS, XML, RSS/Atom, WSDL/SOAP, WebSockets, Comet, JSON, YAML and REST web services.</li>
    <li>Other markup languages: ERB, HAML, Markdown, Textile.</li>
    <li>Frameworks and test automation tools: Rspec, test/unit, Selenium, Webrat, Capybara, Machinist, Faker, JUnit</li>
    <li>Operating Systems: Linux, Windows and real-time Linux with Xenomai patch.</li>
    <li>Web Frameworks: Ruby on Rails, Grails.</li>
    <li>DBMS: PostgreSQL, MySQL, MS SQL Server and Firebird.</li>
    <li>Network infrastructure knowledge: firewall, routing, SSH, SFTP, HTTP.</li>
    <li>Javascript Libraries: jQuery (strong skill) and Prototype.</li>
    <li>Version Control System: Git (strong skill), Subversion and CVS.</li>
    <li>Active <a href="http://www.google.com.br/search?q=%22Rodrigo+Rosenfeld+Rosas%22">participation</a> in open-source community with some contributions to big open-source projects such as Gitorious, Redmine and Rails.</li>
  </ul>
</div>

<h3>Personal Details</h3>
<div class="description">
  <div><strong>Rodrigo Rosenfeld Rosas</strong>, Brazilian, married, <%= ((DateTime.now - DateTime.new(1981, 6, 13))/365).to_i %> years old (13/06/1981).</div>
  <div><strong>Permanent</strong>: Presidente Pedreira, 145, ed. Vicmar, ap. 602,</div>
  <div>Parque Moscoso,</div>
  <div>Vitória - ES,</div>
  <div>Brazil - 29018-025</div>
  <div><strong>Phone:</strong> (27) 3082-6309 / 8803-2664</div>

  <div><strong>Languages: </strong>Portuguese, English, Spanish</div>
</div>

</body>
</html>